config/routes.rb
Rails.application.routes.draw do
  root to: 'lists#index'
  resources :lists, only: %i[show new create] do
    resources :bookmarks, only: %i[new create]
    resources :reviews, only: %i[new create]
  end

  resources :reviews, only: %i[destroy]
  resources :bookmarks, only: %i[destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :comment, length: { minimum: 6 }
  validates_uniqueness_of :movie, scope: :list
end

app/models/list.rb
class List < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :photo, presence: true
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  has_many :reviews
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, :overview, presence: true, uniqueness: true
  has_many :bookmarks
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :list
  validates :content, presence: true
  validates :rating, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]
  before_action :set_bookmark, only: %i[destroy]
  before_action :movies, only: %i[new create]

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      @bookmark = @list.bookmarks
      render 'lists/show', status: :unprocessable_entity
    end
  end

  def destroy
    @list = @bookmark.list
    @bookmark.destroy
    redirect_to list_path(@list), status: :see_other
  end

  private

  def set_bookmark
    @bookmark = Bookmark.find(params[:id])
  end

  def movies
    @movies = Movie.all
  end

  def set_list
    @list = List.find(params[:list_id])
  end

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id, :list_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: %i[show]

  def index
    @lists = List.all
  end

  def show
    @review = Review.new(list: @list)
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_list, only: %i[new create]
  before_action :set_review, only: %i[destroy]

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.list = @list
    if @review.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @list = @review.list
    @review.destroy
    redirect_to list_path(@list), status: :see_other
  end

  private

  def set_list
    @list = List.find(params[:list_id])
  end

  def set_review
    @review = Review.find(params[:id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/bookmarks/new.html.erb
<h1>Bookmark Movie</h1>

<%= simple_form_for [@list, @bookmark] do |f| %>
  <%= f.association :movie, collection: @movies %>
  <%= f.input :comment%>
  <%= f.submit 'Add' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<div class="navbar">
  <i class="fad fa-popcorn"></i>
  <%= link_to 'Create List', new_list_path, class: 'btn btn-primary' %>
</div>

<div class="banner" style="background-image: linear-gradient(90deg, rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= image_path 'banner-image.jpg' %>)">
  <h1>Lists</h1>
</div>


<div class="container cards">

      <% @lists.each do |l| %>
        <% if l.photo.attached? %>
          <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url('<%= cl_image_path l.photo.key %>')">
        <% else %>
          <div class="card-category">
        <% end %>
        <%= link_to l.name, list_path(l) %>
        </div>
      <% end %>

</div>

app/views/lists/new.html.erb
<h1>Add List</h1>

<%= simple_form_for(@list) do |l| %>
    <%= l.input :name, placeholder: 'Mission Cléopatre' %>
    <%= l.input :photo, as: :file %>
    <%= l.submit :submit %>
<% end %>

<br>
<%= link_to 'Lists', root_path, class: 'btn btn-success'  %>

app/views/lists/show.html.erb
<div class="navbar">
  <i class="fad fa-popcorn"></i>
  <div>
    <%= link_to 'Lists', root_path, class: 'btn btn-success'  %>
    <%= link_to 'Add Movie', new_list_bookmark_path(@list), class: 'btn btn-primary' %>
  </div>
</div>

<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4), rgba(0,0,0,0.4)), url('<%= cl_image_path @list.photo.key %>')">
  <h1><%= @list.name %></h1>
</div>

<ul>
  <% @list.movies.each do |m| %>
    <li><%= m.title %></li>
    <% bookmark = Bookmark.find_by(list: @list, movie: m) %>
    <%= link_to "Delete", bookmark_path(bookmark), data: { turbo_method: :delete, turbo_confirm: "Do you want to remove this movie ?" } %>
  <% end %>
</ul>

<%= simple_form_for [@list, @review] do |l| %>
    <%= l.input :content %>
    <%= l.input :rating %>
    <%= l.submit :submit %>
<% end %>

<ul>
  <% @list.reviews.each do |r| %>
    <li><%= r.content %></li>
    <li><%= r.rating %></li>
    <%= link_to "Delete", review_path(r), data: { turbo_method: :delete, turbo_confirm: "Do you want to remove this movie ?" } %>
  <% end %>
</ul>